export default Type={
    INCREAMENT: 'INCREAMENT',
    DECREAMENT: 'DECREAMENT',
    ADDCOMMENT: 'ADDCOMMENT',
    EDIT:'EDIT',
    GET_PERSON: 'GETPERSON',
    SHOW_PEOPLE: 'SHOWPEOPLE',
    UPDATE_COVER_PHOTO: 'UPDATECOVER',
}